import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import mainImage from '@/assets/images/ucla.jpg'
import { Button, Form, Spinner } from 'react-bootstrap'
import { FormEvent, useState } from 'react'

export default function Home() {

  const [answer, setAnswer] = useState("");
  const [answerLoading, setAnswerLoading] = useState(false);
  const [answerLoadingError, setAnswerLoadingError] = useState(false);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const formData = new FormData(event.target as HTMLFormElement);
    const prompt = formData.get("prompt")?.toString().trim();
    //trim removes any white spaces before or after
    if (prompt) {
      try {
        setAnswer("")
        setAnswerLoadingError(false)
        setAnswerLoading(true)
        //encodeURIComponent takes care of encoding any special characters like spaces or percentage signs so they can be in the URL
        const response = await fetch("/api/ucla?prompt=" + encodeURIComponent(prompt))
        const body = await response.json();
        setAnswer(body.answerText)

      } catch (error) {
        console.log(error)
        setAnswerLoadingError(true);
      } finally {
        setAnswerLoading(false);
      }
    }


  }

  return (
    <>
      <Head>
        <title>AI App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>UCL-AI</h1>
        <h2>powered by GPT-3</h2>
        <div>What questions do you have about UCLA?</div>
        <div className={styles.mainImageContainer}>
        <Image
        src={mainImage}
        fill
        alt='A picture of Royce Hall on UCLA Campus'
        priority
        className={styles.mainImage}
        />
        </div>
        <Form onSubmit={handleSubmit} className={styles.inputForm}>
          <Form.Group className='mb-3' controlId='prompt-input'>
            <Form.Label>Ask a question about...</Form.Label>
            <Form.Control
            name='prompt'
            placeholder='e.g. what are the best dining halls on campus?'
            maxLength={100}
            />
          </Form.Group>
          <Button type='submit' className='mb-3' disabled={answerLoading}>
            Ask
          </Button>
        </Form>

        {answerLoading && <Spinner animation='border' />}
        {answerLoadingError && "Something went wrong. Please try again"}
        {answer && <h5>{answer}</h5>}
      </main>
    </>
  )
}
